- name: Asenna redis-server
  apt:
    name: redis-server
    state: present
    update_cache: yes

- name: Portin vaihto
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^port '
    line: 'port 7777'
  notify: Restart Redis
