- name: Enable contrib non-free repositories
  apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }} main contrib non-free non-free-firmware"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install gaming packages
  apt:
    name:
      - steam
      - lutris
      - mangohud
      - gamemode
    state: present

- name: Download Discord .deb package
  get_url: 
    url: "https://discord.com/api/download?platform=linux&format=deb"
    dest: "/tmp/discord.deb"
    force: no

- name: Install Discrd from .deb
  apt:
    deb: "/tmp/discord.deb"

- name: Fix missing dependencies
  apt:
    state: present
    update_cache: yes
