    - name: Ota i386-arkkitehtuuri käyttöön (Steam ja 32-bit ajurit)
      command: dpkg --add-architecture i386
      register: add_arch
      changed_when: false

    - name: Päivitä apt-välimuisti
      apt:
        update_cache: yes

    - name: Lisätään käyttäjälle oikeudet
      user:
        name: "{{ user_name }}"
        groups: video,render
        append: yes

    - name: Asenna avoimet Vulkan-ajurit (AMD / Intel)
      apt:
        name:
          - mesa-vulkan-drivers
          - mesa-vulkan-drivers:i386
          - libvulkan1
          - libvulkan1:i386
          - vulkan-tools
        state: present
      # Huom! NVIDIAn suljetut ajurit asennetaan yleensä 'nvidia-driver-535' tyyppisellä paketilla

    - name: Steam to debian
      apt_repository:
        repo: "deb http://deb.debian.org/debian/ trixie main contrib non-free non-free-firmware"
        state: present

    - name: Asenna pelityökalut repoista (Steam, Lutris, GameMode, MangoHud)
      apt:
        name:
          - steam # Joissain distroissa pelkkä 'steam'
          - lutris
          - gamemode
          - mangohud
        state: present

    - name: Lataa Discord .deb-paketti
      get_url:
        url: "https://discord.com/api/download?platform=linux&format=deb"
        dest: "/tmp/discord.deb"

    - name: Asenna Discord
      apt:
        deb: "/tmp/discord.deb"
        state: present

    # -- KÄYTTÄJÄKOHTAISET ASETUKSET (become: no) --
    - name: Määritä Steamin polku (Debian)
      set_fact:
        steam_path: "/home/{{ user_name }}/.local/share/Steam"

    - name: Luo compatibilitytools.d-hakemisto
      become: no
      file:
        path: "{{ steam_path }}/compatibilitytools.d"
        state: directory
        mode: '0755'

    - name: Lataa Proton-GE väliaikaiskansioon
      become: no
      get_url:
        url: "{{ proton_ge_url }}"
        dest: "/tmp/{{ proton_ge_version }}.tar.gz"
        mode: '0644'

    - name: Pura Proton-GE
      become: no
      unarchive:
        src: "/tmp/{{ proton_ge_version }}.tar.gz"
        dest: "{{ steam_path }}/compatibilitytools.d/"
        remote_src: no # Nyt tiedosto on paikallinen (/tmp)
        creates: "{{ steam_path }}/compatibilitytools.d/{{ proton_ge_version }}"
      notify: Huomauta Steamin uudelleenkäynnistyksestä

    - name: Luo MangoHud-hakemisto käyttäjälle
      become: no
      file:
        path: "/home/{{ user_name }}/.config/MangoHud"
        state: directory
        mode: '0755'

    - name: Kopioi MangoHud-konfiguraatio
      become: no
      copy:
        src: files/MangoHud.conf
        dest: "/home/{{ user_name }}/.config/MangoHud/MangoHud.conf"
        mode: '0644'

