    - name: "Add i386-architecture"
      command: dpkg --add-architecture i386
      register: add_arch
      changed_when: false

    - name: "Update apt cache"
      apt:
        update_cache: yes

    - name: "Adding User to groups (video and render)"
      user:
        name: "{{ user_name }}"
        groups: video,render
        append: yes

    - name: "Installing open Vulkan-drivers (AMD / Intel)"
      apt:
        name:
          - mesa-vulkan-drivers
          - mesa-vulkan-drivers:i386
          - libvulkan1
          - libvulkan1:i386
          - vulkan-tools
        state: present

    - name: "Enable contrib non-free repositories for Steam"
      apt_repository:
        repo: "deb http://deb.debian.org/debian/ trixie main contrib non-free non-free-firmware"
        state: present

    - name: "Install gaming packages (Steam, Lutris, GameMode, MangoHud)"
      apt:
        name:
          - steam
          - lutris
          - gamemode
          - mangohud
        state: present

    - name: "Download Discord .deb package"
      get_url:
        url: "https://discord.com/api/download?platform=linux&format=deb"
        dest: "/tmp/discord.deb"

    - name: "Install Discrd from .deb"
      apt:
        deb: "/tmp/discord.deb"
        state: present

    - name: "Naming Steam path."
      set_fact:
        steam_path: "/home/{{ user_name }}/.local/share/Steam"

    - name: "Adding compatibilitytools.d-directory"
      become: no
      file:
        path: "{{ steam_path }}/compatibilitytools.d"
        state: directory
        mode: '0755'

    - name: "Download Proton-GE to a temporary folder"
      become: no
      get_url:
        url: "{{ proton_ge_url }}"
        dest: "/tmp/{{ proton_ge_version }}.tar.gz"
        mode: '0644'

    - name: "Unpack Proton-GE"
      become: no
      unarchive:
        src: "/tmp/{{ proton_ge_version }}.tar.gz"
        dest: "{{ steam_path }}/compatibilitytools.d/"
        remote_src: no
        creates: "{{ steam_path }}/compatibilitytools.d/{{ proton_ge_version }}"
      notify: Notify Steam restart

    - name: "Making MangoHud-directory to user"
      become: no
      file:
        path: "/home/{{ user_name }}/.config/MangoHud"
        state: directory
        mode: '0755'

    - name: "Copy MangoHud.conf"
      become: no
      copy:
        src: files/MangoHud.conf
        dest: "/home/{{ user_name }}/.config/MangoHud/MangoHud.conf"
        mode: '0644'

