- name: Create MangoHud config directory 
  file: 
    path: "/home/{{ ansible_env.USER }}/.config/MangoHud"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: '0755'

- name: Create MangoHud config
  copy:
    dest: "/home/{{ ansible_env.USER }}/.config/MangoHud/MangoHud.conf"
    content: |
      fps_limit=60
      cpu_temp
      gpu_temp
    owner: "{{ ansible_env.USER }}"
    mode: '0644'
