- name: "Pakettien asennus"
  hosts: all
  become: yes

  tasks:
    - name: "Asenna git ja curl"
      apt:
        name:
          - git
          - curl
        state: present
        update_cache: yes
