    user_name: "{{ lookup('env', 'USER') }}"
    proton_ge_version: "GE-Proton8-25"
    proton_ge_url: "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/{{ proton_ge_version }}/{{ proton_ge_version }}.tar.gz"
