- group:
    name: "sudoless"
    state: present
- user:
   name: "jari"
   state: present
   groups: ["sudoless", "sudo", "adm"]
- authorized_key:
    user: "jari"
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPK3YUkWHETwHZhmkkunWPMXmXN9tY8ov7YZQHf29h3h perttu@perttu-virtualbox"
- copy:
    dest: "/etc/sudoers.d/sudoless"
    content: "%sudoless ALL = (ALL) NOPASSWD: ALL\n"
    owner: "root"
    group: "root"
    mode: "0644"
